#ifndef UTIL_CONFIG_H
#define UTIL_CONFIG_H

typedef enum
{
    CONFIG_CMD_LOADALL,
    CONFIG_CMD_SAVEALL,
    CONFIG_CMD_RESETALL,
    CONFIG_CMD_SET_BUTTONMAP,
    CONFIG_CMD_SET_DPADMODE,
    CONFIG_CMD_SET_CALIBRATE,
    CONFIG_CMD_SET_REMAP,
    CONFIG_CMD_SET_COLOR
} util_config_cmd_t;

#endif